FROM nvidia/cuda:13.2.0-cudnn-runtime-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y git wget unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y \
    && apt-get clean

# Install a specific conda version to avoid python conflict version (conda requires python>3.11 and <3.12)

RUN mkdir -p /opt/conda \
    && wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.11.1-0-Linux-x86_64.sh -O /opt/conda/miniconda.sh \
    && bash /opt/conda/miniconda.sh -b -u -p /opt/conda \
    && rm /opt/conda/miniconda.sh


# Update PATH to use conda during this build phase
ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"

# Get mochi build
RUN wget https://github.com/mochi-hpc/mochi-conda-packages/releases/download/2026-03-17/mochi-conda-channel-2026-03-17-linux-64-py3.12.tar.gz \
    && mkdir /mochi-conda \
    && tar -xzf mochi-conda-channel-2026-03-17-linux-64-py3.12.tar.gz -C /mochi-conda


# Install conda packages
RUN conda install -qy conda==24.11.1 pip python=3.12 \
    && conda install -c anaconda git \
    && conda install libffi==3.4.2 \
    && conda install --channel conda-forge lalsuite \
    && conda install --channel /mochi-conda diaspora-stream-api diaspora-stream-octopus \
    && conda clean --all --force-pkgs-dirs --yes 

ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"

COPY ./gravitational_wave /app
WORKDIR /app

# Install dependencies
RUN . activate base && cd /app \ 
    && pip install -e ".[examples]" \
    && pip install -r requirements.txt \
    && pip install torch torchvision torchaudio gdown git+https://github.com/diaspora-project/stream-interface.git

RUN gdown 1zuNzPzHGlk0e5cUCDDPkZjZ5v81J-rhS \
    && unzip MMA_GravitationalWave_Data.zip \
    && rm MMA_GravitationalWave_Data.zip 