FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --no-install-recommends -y git wget unzip \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y \
    && apt-get clean

# Install a specific conda version to avoid python conflict version (conda requires python>3.11 and <3.12)

RUN mkdir -p /opt/conda \
    && wget https://repo.anaconda.com/miniconda/Miniconda3-py310_24.11.1-0-Linux-x86_64.sh -O /opt/conda/miniconda.sh \
    && bash /opt/conda/miniconda.sh -b -u -p /opt/conda \
    && rm /opt/conda/miniconda.sh


# Update PATH to use conda during this build phase
ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"

# Install conda packages
RUN conda install -qy conda==24.11.1 pip python=3.10 \
    && conda install --channel conda-forge lalsuite \
    && conda clean --all --force-pkgs-dirs --yes

ENV PATH="/opt/conda/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/conda/lib:$LD_LIBRARY_PATH"

COPY . /app
WORKDIR /app

# Install dependencies
RUN . activate base && cd /app \ 
    && pip install -e ".[examples]" \
    && pip install -r requirements.txt \
    && pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 gdown

RUN gdown 1zuNzPzHGlk0e5cUCDDPkZjZ5v81J-rhS \
    && unzip MMA_GravitationalWave_Data.zip \
    && rm MMA_GravitationalWave_Data.zip 